name: Build Python Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      manual:
        description: "Trigger the workflow manually"
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Build Package
        run: python setup.py sdist bdist_wheel

      - name: Check Build
        run: |
          twine check dist/*

      - name: Install Package
        run: pip install .

      - name: Create Temporary Directory
        run: echo "TMP_DIR=$(mktemp -d)" >> $GITHUB_ENV

      - name: Test Excel
        run: |
          python e2e/test-excel.py
          echo "Contents of Temp Directory:"
          ls -l ${{ env.TMP_DIR }}
          if [ -z "$(ls -A ${{ env.TMP_DIR }})" ]; then
             echo "Temp directory is empty"
             exit 1
          else
             echo "Temp directory is not empty"
          fi
        env:
          TEMP_DIR: ${{ env.TMP_DIR }}
